name: Run Unittests
on:
    push:
        branches:
            - 1-establish-tdd-process-linked-to-project-items
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: self-hosted
        env:
          ACTIONS_RUNNER_LABELS: github-101
          ACTIONS_RUNNER_DEBUG: true
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11.9'
                cache: 'pip'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: get environment
              run: |
                env
                pwd
                ls ./test/extract_test.py
            - name: Run tests with unittest
              run:  python -m unittest test/test_extract.py
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                files: test-results.xml
