name: Run Unittests
on: push
jobs:
    build:
        runs-on: self-hosted
        env:
          ACTIONS_RUNNER_LABELS: github-101
          ACTIONS_RUNNER_DEBUG: true
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11.9'
                cache: 'pip'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests with unittest
              run: pytest --junitxml=test-results.xml
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                files: test-results.xml
